#!/bin/bash

VERB=${1:-"help"}

PROJECT_DIR=${PROJECT_DIR:-$PWD}
PROJECT_FILE=${PROJECT_FILE:-"${PROJECT_DIR}/sbs.project"}

source ${HOME}/.local/share/sbs/verbs_builtins.bash
source ${PROJECT_DIR}/sbs.verbs

if [[ $(type -t ${VERB}) = "function" && ! ${NOT_VERB[@]} =~ (^|[[:space:]])"${VERB}"($|[[:space:]]) ]]; then
    ${VERB}
else
    echo "Unknown verb: ${VERB}"
fi
